### ISSUE TITLE
Usage of the Span<T> and Memory<T>

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [lukasz-pyrzyk/Kronos#75]
https://github.com/dotnet/corefxlab/blob/master/docs/Span.md

**Comment by sometowngeek** [comment]
The link is broken. Does this still need help?

**Comment by lukasz-pyrzyk** [comment]
Hi @sometowngeek !

Span<T> was moved to https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Span.cs

If you see any options of improvement, please don't hesitate to create a PR
