### ISSUE TITLE
Create OSX build

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [lukasz-pyrzyk/Kronos#96]
awaiting https://github.com/dotnet/corefx/issues/9394

**Comment by owlstack** [comment]
What is needed to create the OSX Build? I can help but not sure what you mean by create the build. Thanks!

**Comment by lukasz-pyrzyk** [comment]
Hi @owlstack !
It would be great to have pipeline for OSX Build. Currently we have it for Windows (Appveyor) and Linux (Travis).

Travis offers a MacOS build, however, it was not working in the past

**Comment by lukasz-pyrzyk** [comment]
Not needed...
